# baseline.yaml - Production configuration baseline
# This file is locked via SHA256 hash in production

env: dev

time:
  days_per_year: 365.25
  min_hours_to_expiry: 0.10
  max_days_to_expiry: 180

logging:
  level: INFO
  to_file: true
  json: true
  filename: logs/app.log
  max_bytes: 20971520  # 20MB
  backup_count: 5
  utc: true

# --- DEBUG ---:
debug:
  enabled: true     # enable one-off raw dumps and extra tracing on debug runs
  dump_dir: "debug_runs"
  capture:
    polymarket: true  # save Polymarket markets/events
    options: true     # save Lyra options chains
    perps: true       # save Lyra perps snapshots
    snapshot: true    # save orchestrator scanners/opportunities snapshot
    checkpoint: true  # save step-by-step debugging checkpoints
  log:
    reason_codes: true
    reason_codes_level: DEBUG   # or INFO
    reason_codes_max_lines: 400
    per_currency_snapshot: true
    ev_summary_info: true

lyra:
  api_base: https://api.lyra.finance
  ws_uri: wss://api.lyra.finance/ws
  options_currencies:
    BTC: BTC
    ETH: ETH
  perps_currencies:
    BTC: BTC-PERP
    ETH: ETH-PERP
    SOL: SOL-PERP
    XRP: XRP-PERP
    DOGE: DOGE-PERP

execution:
  # Risk & sizing
  risk_free_rate: 0.05
  min_risk_reward_ratio: 1.0
  min_kelly_fraction: 0.005
  kelly_fraction_cap: 0.50

  # Position sizing (for calc defaults; not a hard capacity limit)
  default_position_size: 100.0
  max_position_size: 1000.0
  min_position_size: 10.0
  
  # Instrument capture for automated trading
  capture_instruments: true   # Capture execution details for automated trading
  # position_base_unit: 100.0  # DEPRECATED alias for default_position_size; use default_position_size instead

  # Spread / hedging tolerances
  hedge_combination_mode: offset
  min_spread_threshold: 0.01
  max_spread_allowed: 0.05
  default_spread_width_pct: 0.03
  min_spread_width: 0.5
  max_spread_count: 10000
  settle_spread_at_pm_expiry: true
  # How to value option hedges when PM resolves before option expiry
  #   intrinsic_only: treat PM resolution as option expiry (model-free, conservative)
  #   sticky_strike:  Black–Scholes using same strike IV and reduced time (default)
  options_unwind_model: sticky_strike
  post_event_vol_drop: 0.0
  # --- Arbitrage classification controls (strict, model-free) ---
  strict_arbitrage_mode: true          # detector-approved true arbs bypass EV/Kelly gates
  label_true_arb_from_detector: true   # only detector sets 'true arbitrage' label
  # --- Strict anchoring / scanning policy ---
  # If true, a detector-approved "true arbitrage" MUST be anchored at exact K.
  # Opportunities built from brackets K1<K<K2 are retained only as "near-arb".
  exact_strike_required_for_true_arb: true
  # If true, when no option_expiry is specified, the scanner will try ALL expiries
  # to find an exact-K anchored digital, falling back to near-arb if none exists.
  consider_all_expiries: true

  # Options trading frictions (bps)
  option_fee_bps: 30.0
  option_slippage_bps: 20.0

  # Expected value / quality gates
  min_expected_value: 0.03
  min_sharpe_ratio: 0.20
  max_acceptable_loss: 250.0
  transaction_cost_rate: 0.002

market_impact:
  gamma:
    BTC: 0.10
    ETH: 0.14
    SOL: 0.22
    XRP: 0.25
    DOGE: 0.27

ranking:
  # Probability blending
  blend_mode: precision
  fixed_weight: 0.5

  # Risk penalties
  vega_penalty_lambda: 0.25
  funding_penalty_kappa: 0.80
  liquidity_penalty_theta: 0.0005

  # Liquidity / market impact
  market_impact_coefficient: 0.05

  # Quality tier thresholds (looser to surface more)
  true_arbitrage_dni_threshold: 0.0    # detector enforces two-state non-negativity
  near_arbitrage_dni_threshold: -150.0
  near_arbitrage_prob_threshold: 0.70
  high_probability_threshold: 0.60
  moderate_probability_threshold: 0.45

  # Probability clipping & dependence controls
  probability_clip_floor: 0.01
  probability_clip_ceiling: 0.995
  min_correlation_threshold: 0.10
  covariance_regularization: 0.00001

data:
  save_detailed_data: true
  save_unfiltered_opportunities: true
  scan_interval_seconds: 180
  data_retention_minutes: 120
  orderbook_depth: 20

polymarket:
  include_dailies: true          # keep daily markets even if they expire very soon
  dailies_window_hours: 24       # treat markets expiring within next 24h as dailies
  filter_closed: true            # drop closed markets
  filter_active: true            # keep only active markets

hedging:
  quadratic:
    # objective
    regularization: 1.0e-8
    cost_budget: 0.0
    include_bonds: true
    include_forwards: true

    # sparse helper
    use_sparse_helper: true
    max_legs: 8
    bond_basis_name: bond_T1

    # rounding per asset (set per venue)
    contract_increment_by_asset:
      BTC: 0.01      # Lyra/Derive allows 0.01 increments
      ETH: 0.01      # Lyra/Derive allows 0.01 increments
    min_contracts_by_asset:
      BTC: 0.01
      ETH: 0.01
    min_notional: 25.0
  
  variance:
    # --- Expiry selection policy (moved from config/defaults.yaml) ---
    # Which expiries to consider relative to the PM resolution date:
    # - nearest_on_or_after (safe default)
    # - allow_far_with_unwind (requires execution.options_unwind_model != intrinsic_only)
    expiry_policy: allow_far_with_unwind
    # Max days AFTER PM we allow when selecting additional expiries (only used with allow_far_with_unwind).
    # Clamped to [0, 60] in config_manager.
    max_expiry_gap_days: 60
    # How many expiries to consider (closest first). Clamped to [1, 10] in config_manager.
    max_expiries_considered: 10
    # Require two-sided live quotes for tradable legs.
    require_live_quotes_for_trades: true
    # Restrict sparse candidate strikes to [ (1-w)*K0, (1+w)*K0 ] on OTM side. Clamped to [0.05, 0.50].
    strike_proximity_window: 0.25
    # For an expiry to count as "valid", require at least this many instruments with BOTH bid>0 and ask>0.
    # Clamped to [2, 20].
    min_quotes_per_expiry: 2
    # Minimum number of strikes required post-filter to attempt replication (calls+puts combined).
    min_strikes_required: 6
    # objective
    regularization: 1.0e-8
    cost_budget: 0.0
    include_bonds: true
    include_forwards: true
    # Feature flags & tolerances (variance swap)
    pm_anchored_static_replication: true
    cost_recovery_tol: 0.02
    digital_width_bps: 50
    clean_quotes: true
    no_arb_enforce: true
    
    # sparse helper
    use_sparse_helper: true
    max_legs: 8
    bond_basis_name: bond_T1
    
    # rounding per asset (set per venue)
    contract_increment_by_asset:
      BTC: 0.01
      ETH: 0.01
    min_contracts_by_asset:
      BTC: 0.01
      ETH: 0.01
    min_notional: 25.0
    
    # PM digital bounds gate
    use_pm_digital_bounds: true
    enforce_pm_digital_bounds: false     # start SOFT; set true only if you want pruning
    pm_bounds_inclusive: false
    pm_bounds_slack_abs: 0.02
    pm_bounds_slack_rel: 0.01
    pm_bounds_use_tradable: true
    pm_bounds_require_two_sided: false
    pm_bounds_max_rel_width: 0.02
    pm_gate_use_pm_strike: true
    
    # --- Liquidity-aware variance builder ---
    variance_forward_must_be_in_range: false
    variance_forward_clip_to_range: true
    variance_zero_bid_truncation_mode: "one_sided"   # keep more strikes than strict VIX mode
    variance_zero_bid_streak: 2
    variance_require_both_wings: false                # ALLOW one-sided expiries (penalize instead of reject)
    variance_min_wing_quotes: 1
    variance_one_sided_rel_spread: 0.05
    variance_one_sided_abs_spread: 0.00
    variance_penalty_bps_per_one_sided: 5.0
    variance_penalty_bps_missing_wing: 25.0
    variance_penalty_bps_per_day_gap: 2.0
