execution:
  # existing execution settings…
  # How to reprice options if we unwind them at the PM resolution time.
  # Allowed: intrinsic_only | sticky_strike | sticky_delta | sticky_moneyness
  options_unwind_model: sticky_strike

debug:
  enabled: true     # enable one-off raw dumps and extra tracing on debug runs
  dump_dir: "debug_runs"
  capture:
    polymarket: true  # save Polymarket markets/events
    options: true     # save Lyra options chains
    perps: true       # save Lyra perps snapshots
    snapshot: true    # save orchestrator scanners/opportunities snapshot
  log:
    reason_codes: true
    reason_codes_level: DEBUG   # or INFO
    reason_codes_max_lines: 400
    per_currency_snapshot: true
    ev_summary_info: true

hedging:
  variance:
    # Which expiries to consider relative to the PM resolution date:
    # - nearest_on_or_after (safe default)
    # - allow_far_with_unwind (requires execution.options_unwind_model != intrinsic_only)
    expiry_policy: allow_far_with_unwind
    # Max days AFTER PM we allow when selecting additional expiries (only used with allow_far_with_unwind).
    # Clamped to [0, 60] in config_manager.
    max_expiry_gap_days: 60
    # How many expiries to consider (closest first). Clamped to [1, 10] in config_manager.
    max_expiries_considered: 10
    # Require two-sided live quotes for tradable legs.
    require_live_quotes_for_trades: true
    # Restrict sparse candidate strikes to [ (1-w)*K0, (1+w)*K0 ] on OTM side. Clamped to [0.05, 0.50].
    strike_proximity_window: 0.25
    # For an expiry to count as "valid", require at least this many instruments with BOTH bid>0 and ask>0.
    # Clamped to [2, 20].
    min_quotes_per_expiry: 2
    # Minimum number of strikes required post-filter to attempt replication (calls+puts combined).
    min_strikes_required: 6